spring.application.name=demo
server.port=8082

camunda.client.mode=saas
camunda.client.auth.client-id=LZIpZW_1SiQE4QAgxsa1cjn-495z9fOH
camunda.client.auth.client-secret=OlzwvZPrVu49A.~AONH2ipjufgBn.~u.tbIWOmIjlvh.dCEVhMXWLLSSe.TOlM7U
camunda.client.cloud.cluster-id=9f6ba8a8-cba2-48c8-8fb2-fb81ccfb87de
camunda.client.cloud.region=sin-2



spring.datasource.url=jdbc:postgresql://localhost:5432/mydb
#spring.datasource.url=jdbc:postgresql://localhost:5432/mydb
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver


camunda.tasklist.base-url=https://sin-2.tasklist.camunda.io/9f6ba8a8-cba2-48c8-8fb2-fb81ccfb87de/v1

camunda.auth.url=https://login.cloud.camunda.io/oauth/token
#camunda.auth.client-id=LZIpZW_1SiQE4QAgxsa1cjn-495z9fOH
#camunda.auth.client-secret=OlzwvZPrVu49A.~AONH2ipjufgBn.~u.tbIWOmIjlvh.dCEVhMXWLLSSe.TOlM7U
camunda.client.auth.audience=tasklist.camunda.io